# infra/docker-compose.yml
version: '3'

services:
  nginx:
    image: nginx:1.25.0-alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
    environment:
      - TZ=Asia/Tokyo
    extra_hosts:
      - "host.docker.internal:host-gateway"
  blue:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-blue
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Tokyo
  green:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-green
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Tokyo
